language: R
cache: packages
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'add-apt-repository -y ppa:cran/ffmpeg-3'
    packages:
      - libmagick++-dev
      - libpoppler-cpp-dev
